package com.asrai.joinit.util.mail;

import lombok.AllArgsConstructor;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

@Service
@AllArgsConstructor
public class MailService {
    
    private JavaMailSender mailSender;
    private static final String FROM_ADDRESS = "${spring.mail.username}";
    
    public void mailSend(MailDto mailDto) {
        try {
            MailHandler mailHandler = new MailHandler(mailSender);
            mailHandler.setTo(mailDto.getAddress()); // 받는 사람
            mailHandler.setFrom(FROM_ADDRESS); // 보내는 사람
            mailHandler.setSubject("[JOIN-IT] 이메일 인증번호가 도착하였습니다."); // 제목

            String htmlContent =
                "<div style=\"background-color:#1e1e1e\">\n"
                    + "\t<!--[if gte mso 9]> <v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\"> <v:fill type=\"tile\" color=\"#1e1e1e\"/></v:background> <![endif]-->\n"
                    + "\t<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                    + "\t\t<tr>\n"
                    + "\t\t\t<td valign=\"top\" align=\"center\">\n"
                    + "\t\t\t\t<table bgcolor=\"#ffffff\" style=\"margin:0 auto;\" align=\"center\" id=\"brick_container\" cellspacing=\"0\"\n"
                    + "\t\t\t\t\tcellpadding=\"0\" border=\"0\" width=\"1406\" class=\"email-container\">\n"
                    + "\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t<td width=\"1406\">\n"
                    + "\t\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t<td width=\"1406\" style=\"height:1232px; background-color:#ffffff; \" bgcolor=\"#ffffff\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"100%\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"100%\" align=\"center\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"height:1049px; background-color:#58867a; padding-left:32px; padding-right:32px;\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbgcolor=\"#58867a\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td height=\"109\" style=\"height:109px; min-height:109px; line-height:109px;\"></td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"515\" align=\"center\"><img\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://plugin.markaimg.com/public/abaf45fd/IqtIXvaEufvqqfU5sdrhKkqNvlGpOx.png\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"515\" border=\"0\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\" max-width:515px; width: 100%; height: auto; display: block;\"></td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td height=\"40\" style=\"height:40px; min-height:40px; line-height:40px;\"></td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"100%\" align=\"center\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"line-height:76px;text-align:center;\"><span\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color:#fefeff;font-weight:700;font-family:Arial,Arial,sans-serif;font-size:32px;letter-spacing:-0.02em;line-height:76px;text-align:center;\">혼자라서\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t힘들 때, 함께하는 건강한 습관</span></div>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td height=\"40\" style=\"height:40px; min-height:40px; line-height:40px;\"></td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"947\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"947\" align=\"center\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"height:534px; background-color:#ffffff; border-radius:22px; \"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbgcolor=\"#ffffff\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"line-height:normal;text-align:center;\"><span\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color:#5e5e5e;font-weight:700;font-family:Barlow,Arial,sans-serif;font-size:39px;line-height:normal;text-align:center;\"><br><br>안녕하세요,\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span><span\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color:#5bcba3;font-weight:700;font-family:Barlow,Arial,sans-serif;font-size:39px;line-height:normal;text-align:center;\">환자/치료사</span><span\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color:#5e5e5e;font-weight:700;font-family:Barlow,Arial,sans-serif;font-size:39px;line-height:normal;text-align:center;\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t님<br></span><span\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color:#5e5e5e;font-weight:700;font-family:Barlow,Arial,sans-serif;font-size:23px;line-height:normal;text-align:center;\"><br><br><br></span><span\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color:#0f5953;font-weight:700;font-family:Arial,Arial,sans-serif;font-size:94px;letter-spacing:-0.02em;line-height:normal;text-align:center;\">" + mailDto.getMessage() + "<br></span><span\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color:#5e5e5e;font-weight:700;font-family:Barlow,Arial,sans-serif;font-size:23px;line-height:normal;text-align:center;\"><br><br><br>아이디/비밀번호\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t찾기 이용을 위해<br>상단의 인증 번호를 입력해주시길 바랍니다.</span></div>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td height=\"109\" style=\"height:109px; min-height:109px; line-height:109px;\"></td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t<td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"1405\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"1358\" align=\"center\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"height:183px; background-color:#202d22; padding-left:23.43634033203125px; padding-right:23.43634033203125px;\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbgcolor=\"#202d22\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td height=\"23.43634033203125\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"height:23.43634033203125px; min-height:23.43634033203125px; line-height:23.43634033203125px;\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"100%\" align=\"center\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"line-height:20px;text-align:center;\"><span\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color:#979dad;font-family:Arial,Arial,sans-serif;font-size:15px;line-height:20px;text-align:center;\">개인정보처리방침\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t| 영상정보처리기기 | 운영관리 방침 | 홈페이지 이용약관 | 데이터처리 이용약관</span></div>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td height=\"7.8121137619018555\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"height:7.8121137619018555px; min-height:7.8121137619018555px; line-height:7.8121137619018555px;\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"line-height:20px;text-align:center;\"><span\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color:#979dad;font-family:Arial,Arial,sans-serif;font-size:15px;line-height:20px;text-align:center;\">사업자등록번호\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tS09P12B203 JOIN-IT (당신의 건강과 함께합니다) TEL : 02) 1234-1234 / FAX : 02)\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1234-1234 개인정보 책임자 : 김영민</span></div>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td height=\"7.8121137619018555\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"height:7.8121137619018555px; min-height:7.8121137619018555px; line-height:7.8121137619018555px;\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"line-height:20px;text-align:center;\"><span\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color:#979dad;font-family:Arial,Arial,sans-serif;font-size:15px;line-height:20px;text-align:center;\">Join-It\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tCompany. All Rights Reseved.</span></div>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td height=\"23.43634033203125\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"height:23.43634033203125px; min-height:23.43634033203125px; line-height:23.43634033203125px;\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"140\" align=\"center\"><img\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://plugin.markaimg.com/public/abaf45fd/r7yaB1E4N7r7PjBOnX50h83wlpPSWw.png\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"140\" border=\"0\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\" min-width:140px; width:140px; height: auto; display: block;\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td height=\"23.43634033203125\"\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"height:23.43634033203125px; min-height:23.43634033203125px; line-height:23.43634033203125px;\">\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t\t\t\t</table>\n"
                    + "\t\t\t\t\t\t</td>\n"
                    + "\t\t\t\t\t</tr>\n"
                    + "\t\t\t\t</table>\n"
                    + "\t\t\t</td>\n"
                    + "\t\t</tr>\n"
                    + "\t</table>\n"
                    + "</div>";
            mailHandler.setText(htmlContent, true); // HTML 레이아웃 적용

//            mailHandler.setAttach("newTest.txt", "static/originTest.txt"); // 첨부파일
//            mailHandler.setInline("join-it-image", "static/join-it-image.png"); // 이미지 삽입

            mailHandler.send();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
