spring:
  # MySQL setting
  datasource:
    # ip, username, password will change
    driver-class-name: org.mariadb.jdbc.Driver
    url: 
    username:  
    password: 
    hikari:
      maximum-pool-size: 3

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  profiles:
    include: oauth

  jpa:
    # JPA query check
    show-sql: true
    # When defining DDL (create, alter, drop), the unique functions of the DB can be used.
    hibernate:
      ddl-auto: update
    # Improves the readability of SQL generated while Hibernate is running.
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 1000
      open-in-view: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true
    transport:
      protocol: smtp
    debug: true
    default-encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            client-id: 
            client-secret: 
            redirect-uri: 
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - name
              - gender
              - birthday
              - phone_number
          #            client-authentication-method: POST
          kakao:
            client-name: Kakao
            client-id: 
            client-secret: 
            redirect-uri: 
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - name
              - gender
              - birthday
              - phone_number
            client-authentication-method: POST
          google:
            client-id: 
            client-secret: 
            redirect-uri: 
            authorization-grant-type: authorization_code
            scope:
#              - account_email
#              - name
#              - gender
#              - birthday
#              - phone_number
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

server:
  port: 5000
  servlet:
    context-path: /api

logging:
  level:
    web: debug


cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    s3:
      bucket: 
      dir:
    region:
      static: ap-northeast-2
    stack:
      auto: false

# openvidu server url 주소 변경 예정
OPENVIDU_URL: 

# openvidu server 비밀번호 변경 예정
OPENVIDU_SECRET: MY_SECRET

#SMS_API_KEY: 
SMS_API_KEY: 
#SMS_API_SECRET_KEY: 
SMS_API_SECRET_KEY:  
SMS_DOMAIN: https://api.coolsms.co.kr
#CALLING_NUMBER: 
CALLING_NUMBER: 

jwt:
  secretKey: 
  access:
    expiration: 3600000 # ms, 60분
    header: Authorization # token 이 저장될 헤더 이름
  refresh:
    expiration: 1209600000 # ms, 2주
    header: Authorization-refresh # token 이 저장될 헤더 이름
