pipeline{
    agent any
    environment {
       BACK_CONTAINER_NAME="spring-container"
       BACK_NAME="byeonghunsong/project:spring-img"
       READ_PATH="/var/lib/docker/tmp/buildkit-**/*"
    }
    stages {
        stage('Clean'){
            steps{
                script {
                    try{
                        sh "docker kill ${BACK_CONTAINER_NAME}"
                        sleep 1
                        sh "docker rm ${BACK_CONTAINER_NAME}"
                        sh "docker image rm ${BACK_NAME}"
                    }catch(e){
                        sh 'exit 0'
                    }
                }
            }
        }
        stage('Build') {
            steps {
                script{
                    sh "sudo -i && cd ~"
                    sh "cd ../../../../../"
                    sh "echo /var/lib/jenkins/workspace/Dev-Be-Test-Pipeline@tmp/Develop/BackEnd/joinit/Dockerfile > ${READ_PATH}"
                    sh "docker build -t ${BACK_NAME} . -f Dockerfile"
                    sh "docker push ${BACK_NAME}"
                }

            }
        }
        stage('Deploy'){
            steps {
                
                sh "docker run -d --name ${BACK_CONTAINER_NAME} -p 8080:8080 ${BACK_NAME}"
                sh "docker image prune --force"
            }
        }
    }
}
